### PR TITLE
Prod: unpin image tag to fix weekly periodic deployment

### PR DESCRIPTION
**Pull request by hcsu**
https://theplanttokyo.atlassian.net/browse/SEC-2538

https://theplanttokyo.atlassian.net/browse/SEC-2539

### CODE REVIEW

**Comment by geckofu** [comment]
@hcsu the periodic deployments should query and use specific image tags instead of `latest`  (btw, could you add link to the deployment configurations?)

**Comment by hcsu** [comment]
The periodic job:

https://github.com/theplant/test-infra/blob/master/prow/jobs/theplant/public/ip2location-nginx.yaml#L133-L189

**Comment by hcsu** [comment]
Ok added some simple comments

**Review by geckofu — APPROVED** [review]

**Pull request merged**
