### PR TITLE
upgraded nginx from 1.14.2 to 1.23.3

### PR DESCRIPTION
**Pull request by idealhack**

### CODE REVIEW

**Comment by idealhack** [comment]
@xuxinx I've released this to the `release-test` branch, can you please verify it's still working as expected?

**Comment by xuxinx** [comment]
Test service works well.

**Review by xuxinx — APPROVED** [review]

**Comment by idealhack** [comment]
I checked some cases, and it seems the results are different, is this because of the database difference, and we are OK to proceed to release to production?

```
$ curl -I -H 'IP2Location-IP: 1.1.1.1' -i 'https://ip2location-test.theplant-dev.com'
HTTP/2 200
date: Wed, 11 Jan 2023 06:14:39 GMT
content-type: application/octet-stream
content-length: 2
ip2location-country-code: US
ip2location-country-name: United States of America
ip2location-region: California
ip2location-city: Los Angeles
ip2location-latitude: 34.052860
ip2location-longitude: -118.243568
ip2location-zipcode: 90001
ip2location-timezone: -08:00
strict-transport-security: max-age=15724800; includeSubDomains

$ curl -I -H 'IP2Location-IP: 1.1.1.1' -i 'https://ip2location-prod.theplant-dev.com'
HTTP/2 200
date: Wed, 11 Jan 2023 06:14:52 GMT
content-type: application/octet-stream
content-length: 2
ip2location-country-code: US
ip2location-country-name: United States of America
ip2location-region: California
ip2location-city: Los Angeles
ip2location-latitude: 34.052231
ip2location-longitude: -118.243683
ip2location-zipcode: 90001
ip2location-timezone: -07:00
strict-transport-security: max-age=15724800; includeSubDomains
```

**Comment by xuxinx** [comment]
Since we cannot determine which/what data is more `correct` (whatever the reason for these differences, the db data is different, or this nginx upgrade), I think it is ok to release.

**Pull request merged**
